-- (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)

SELECT 
CONCAT('/home/grep/src/', GB.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD GB JOIN USED_GOODS_FILE GF
ON GB.BOARD_ID = GF.BOARD_ID
WHERE GB.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;