-- 코드를 입력하세요
SELECT  USER_ID,
        NICKNAME, 
        CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
        CONCAT(LEFT(TLNO,3), '-', MID(TLNO,4, 4), '-', RIGHT(TLNO, 4)) AS '전화번호'
FROM USED_GOODS_BOARD GB JOIN USED_GOODS_USER GU
ON GB.WRITER_ID = GU.USER_ID
GROUP BY GB.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY USER_ID DESC;