-- 코드를 입력하세요
SELECT CC.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR CC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON CC.CAR_ID = RH.CAR_ID
WHERE CAR_TYPE = '세단'
AND START_DATE >= '2022-10-01' AND START_DATE <= '2022-10-31'
GROUP BY CC.CAR_ID
ORDER BY CC.CAR_ID DESC;