-- 코드를 입력하세요
SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES,
        ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW RR JOIN (SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
    ) RI
ON RI.REST_ID = RR.REST_ID
GROUP BY RR.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;